### ISSUE TITLE
Die Eingabefelder "Gastinformationen" sind vorformatierte Textfelder

### ISSUE THREAD

**Issue by sefzikflo** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-iii-team-1#19]
Vorname und Nachname - Freitext (Zeichen beschränkt)
Bankverbindung -
Telefonnummer 
Besonderheiten/Kommentar (Behinderung, Kinder, Hunde …) 
Dauer (Standard: 2 h)

**Comment by PascalWue** [comment]
Geschlossen
