### ISSUE TITLE
Programmiersprache bestimmen für das Frontend

### ISSUE THREAD

**Issue by sefzikflo** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-iii-team-1#4]
Vorgeschlagene Programmiersprachen anschauen - dann Abstimmung

**Comment by PascalWue** [comment]
HTML, Javascript

**Comment by sefzikflo** [comment]
https://iubhfs.sharepoint.com/:w:/r/sites/FallstudieSoftwareEngineering-ThemaIII/Shared%20Documents/General/[Programmiersprachen.docx](https://iubhfs.sharepoint.com/:w:/r/sites/FallstudieSoftwareEngineering-ThemaIII/Shared%20Documents/General/Programmiersprachen.docx?d=w65128d5a55cb4968a6afb56ff70ae244&csf=1&web=1&e=qhtVn1)?d=w65128d5a55cb4968a6afb56ff70ae244&csf=1&web=1&e=qhtVn1
