### ISSUE TITLE
Eine Buchung kann editiert werden

### ISSUE THREAD

**Issue by sefzikflo** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-iii-team-1#40]

**Comment by 2Auri** [comment]
Z.B: Anzahl Personen

**Comment by sefzikflo** [comment]
Buchungs ID nicht anpassbar machen

**Comment by sefzikflo** [comment]
Überprüfung auf Dopplung auch hier geltend machen

**Comment by sefzikflo** [comment]
> [!IMPORTANT]
> Issue-Checkliste:
> - [ ] Code auf Website und Github abgelegt
> - [ ] Integrationstest durch Teamkollege
> - [ ] Abnahme durch Frontend
