### ISSUE TITLE
Ein Buchungseintrag kann gelöscht werden

### ISSUE THREAD

**Issue by sefzikflo** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-iii-team-1#41]

**Comment by 2Auri** [comment]
Steht in Flos Methoden

**Comment by sefzikflo** [comment]
Zusätzlicher Button auf Registrations Seite für Löschen einrichten

**Comment by sefzikflo** [comment]
> [!IMPORTANT]
> Issue-Checkliste:
> - [ ] Code auf Website und Github abgelegt
> - [ ] Integrationstest durch Teamkollege
> - [ ] Abnahme durch Frontend
