### ISSUE TITLE
Datenbankmodellierung testen

### ISSUE THREAD

**Issue by sefzikflo** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-iii-team-1#51]
Definierung Programmiersprache nach ~ 1 Woche

**Comment by martinpri25** [comment]
Beispiel für ein Entity-Relationship-Diagramm

![ER-diagramm](https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-thema-iii-team-1/assets/166112051/c88ce27c-6633-42eb-80bf-f1a41a4367d7)

**Comment by martinpri25** [comment]
Vorschlag: Verwendung von MySQL und IntelliJ; 
Programmiersprachen: HTML (evtl. CSS), Javascript und MySQL

**Comment by sefzikflo** [comment]
Hätte schonmal einen DB-Server erstellt
https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-thema-iii-team-1/blob/fe6ee5534ba9625fddfb4be870fa023bf5171ebb/Backend.md
