### ISSUE TITLE
Mögliche Tische werden gegen Personenzahl geprüft

### ISSUE THREAD

**Issue by 2Auri** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-iii-team-1#64]
Eine Gruppe von 5 Personen möchte reservieren -- > min 5 Plätze frei

**Comment by 2Auri** [comment]
Beispiel: 4 Personen wollen reservieren aber es stehen nur noch Tische mit 2 Sitzplätzen zur Verfügung -- Die Tische mit 2 Sitzplätzen sollen nicht angezeigt werden.

**Comment by sefzikflo** [comment]
Methode vorhanden. Simple Fehlermeldung und Nicht-Annahme der Buchung auf Startseite einbauen

**Comment by sefzikflo** [comment]
erledigt mit #69
