### ISSUE TITLE
Wie lange blockiert eine Buchung einen Tisch? Vor und nach Startzeit?

### ISSUE THREAD

**Issue by 2Auri** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-iii-team-1#66]
Bestimmen welches Intervall (Wie lange?)

**Comment by sefzikflo** [comment]
Aktuell 1 Stunde

**Comment by sefzikflo** [comment]
> [!IMPORTANT]
> Issue-Checkliste:
> - [ ] Code auf Website und Github abgelegt
> - [ ] Integrationstest durch Teamkollege
> - [ ] Abnahme durch Frontend
