### ISSUE TITLE
Freie Tische werden angezeigt anhand der Schnittstelle (bsp. Ajax, Jason)

### ISSUE THREAD

**Issue by 2Auri** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-iii-team-1#69]
Hängt auch mit issue 16 zusammen.

**Comment by 2Auri** [comment]
Hängt auch mit Issue 12 zusammen

**Comment by sefzikflo** [comment]
Simple Textrückmeldung noch möglich (wenn Zeit)?

**Comment by sefzikflo** [comment]
Wird auf Startseite nach Personenangabe angezeigt. Aktuell immer noch zur davor eingegeben Zahl.
Code hochladen!

**Comment by sefzikflo** [comment]
> [!IMPORTANT]
> Issue-Checkliste:
> - [ ] Code auf Website und Github abgelegt
> - [ ] Integrationstest durch Teamkollege
> - [ ] Abnahme durch Frontend
