### ISSUE TITLE
Ordnerstruktur im Code mit Frontend klären

### ISSUE THREAD

**Issue by 2Auri** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-iii-team-1#70]
Main, Backend, Prototyp,....

**Comment by sefzikflo** [comment]
Filesystem der Website aufräumen. /Test Unterordner entfernen?

**Comment by sefzikflo** [comment]
Todo: Alles in Passwortgeschützten Ordner, damit nur auf die gewünschten Seiten zugegriffen werden kann
