### ISSUE TITLE
Möglichkeit geben die zeitliche Dauer der Buchung anzupassen

### ISSUE THREAD

**Issue by 2Auri** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-iii-team-1#72]

**Comment by sefzikflo** [comment]
Mit Frontend vereinbart vorerst Dauer 2 Stunden

**Comment by sefzikflo** [comment]
> [!IMPORTANT]
 > Issue-Checkliste:
 > - [ ] Code auf Website und Github abgelegt
 > - [ ] Integrationstest durch Teamkollege
 > - [ ] Abnahme durch Frontend
