### ISSUE TITLE
Uhrzeit auf 15min anpassen

### ISSUE THREAD

**Issue by PascalWue** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-iii-team-1#84]

**Comment by PascalWue** [comment]
Erledigt

**Comment by TanjaHrtl** [comment]
Wir müssen da noch schauen, weil das Restaurant hat ja nicht jeden Tag immer von 10 Uhr bis 22 Uhr offen. Oft ist so ein Restaurant ja auch um Mittag oder frühen Nachmittag rum geschlossen.
Hier als Beispiel:
Öffnungszeiten Delphi Rosenheim:
täglich von 11:00 bis 14:30 und von 17:00 bis 22:30
