### ISSUE TITLE
Wenn ein Tisch zu einer Uhrzeit bereits belegt ist, wird die Buchung nicht angenommen

### ISSUE THREAD

**Issue by 2Auri** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-iii-team-1#85]
Wenn es die Reservierung schon gibt soll es eine Fehlermeldung geben. Die Fehlermeldung soll dann mit einem Ok beendet werden.

**Comment by sefzikflo** [comment]
Meldung auf Redirect Seite eingerichtet und Buchung wird nicht angenommen.
Noch ToDo: Auf Startseite bleiben und Daten bleiben in Eingabefeldern
