### ISSUE TITLE
Neue Abfrage für Login Daten

### ISSUE THREAD

**Issue by 2Auri** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-iii-team-1#92]
Gehört zu Issue 91

**Comment by 2Auri** [comment]
Absprache mit Herr Schlosser am 21.06.2024

**Comment by sefzikflo** [comment]
> [!IMPORTANT]
> Issue-Checkliste:
> - [ ] Code auf Website und Github abgelegt
> - [ ] Integrationstest durch Teamkollege
> - [ ] Abnahme durch Frontend

**Comment by sefzikflo** [comment]
Code ablegen! Passwort wird bei Useranlage gehasht

**Comment by sefzikflo** [comment]
Login soll gegen gehashtes Passwort prüfen.

**Comment by sefzikflo** [comment]
> [!IMPORTANT]
> Issue-Checkliste:
> - [x] Code auf Website und Github abgelegt
> - [x] Integrationstest durch Teamkollege
> - [ ] Abnahme durch Frontend
